function [scenario, egoVehicle, egoWaypoints, allrefPaths, allStatus] = ds6_lanes_roadWith5Cars_stucked()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.14 (R2023a) and Automated Driving Toolbox 3.7 (R2023a).
% Generated on: 11-Aug-2023 16:29:34

% Construct a drivingScenario object.
scenario = drivingScenario("SampleTime", 1.0, "StopTime", 25.0);
allrefPaths = cell(0);
allStatus = cell(0);
egoWaypoints = [-57.310124330798 -5.65795699867872 0;
    -5.8 -5.9 0;
    21.5 -5.6 0;
    52.4 -5.8 0;
    74.8 -5.6 0;
    96.7 -6 0];

% Add all road segments
roadCenters = [-68.9 -0.5 0;
    100.2 0 0];
marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Dashed')
    laneMarking('DoubleSolid', 'Color', [0.9 0.9 0.3])
    laneMarking('Dashed')
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(6, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

roadCenters = [8.1 70.8 0;
    7.2 -79.3 0];
marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Dashed')
    laneMarking('DoubleSolid', 'Color', [0.96 0.98 0.3])
    laneMarking('Dashed')
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(6, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road1');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-57.310124330798 -5.65795699867872 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
% speed = [5;5;5;5;5;5];
% trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-9.6 -2.3 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
allrefPaths{numel(allrefPaths) + 1} = [-9.6 -2.3 0 0 0 0];

vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-47.7 -5.5 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car2');
allrefPaths{numel(allrefPaths) + 1} = [-40.7 -5.5 0 0 0 0];

vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-20.4 -2.3 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car3');
allrefPaths{numel(allrefPaths) + 1} = [-20.4 -2.3 0 0 0 0];

vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [10.7 -5.7 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car4');
allrefPaths{numel(allrefPaths) + 1} = [-1.7 -5.7 0 0 0 0];

vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-34.1 -9.3 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car5');
allrefPaths{numel(allrefPaths) + 1} = [-34.1 -9.3 0 0 0 0];
